### ISSUE TITLE
source missing for modules/static/browser-matrix.min.js

### ISSUE THREAD

**Issue by jonassmedegaard** [matrix-construct/construct#173]
Where is the true source for the minified file `modules/static/browser-matrix.min.js`?

Commit 59e05b4 seems to indicate that it is something that in 2017 was something called "Client Alpha (Chlamydia Client)".

Does that code live somewhere in source form?

Reason I ask is that I im currently looking into packaging Construct officially for Debian, where it is not permitted to distribute source-less code (which includes minified code).

**Comment by jevolk** [comment]
> Where is the true source for the minified file modules/static/browser-matrix.min.js

That appears to be a minified release of https://github.com/matrix-org/matrix-js-sdk. There is also a minified release of Angular. This may indeed open up some license complications. First of all, none of that `modules/static` (or I believe it's called `share/` now) is essential to Construct's operation. The client existed for early testing and has since bitrot from several changes to Matrix over the years and is not used; adds no value to a package at this time.

I'll try to get this split off into some optional submodule as soon as I can. Thanks for the heads up.

**Comment by jonassmedegaard** [comment]
Quoting Jason Volk (2020-12-22 22:34:16)
> > Where is the true source for the minified file modules/static/browser-matrix.min.js
> 
> That appears to be a minified release of https://github.com/matrix-org/matrix-js-sdk.

Ah, of course.


> There is also a minified release of Angular. This may indeed open up some license complications. First of all, none of that `modules/static` (or I believe it's called `share/` now) is essential to Construct's operation. The client existed for early testing and has since bitrot from several changes to Matrix over the years and is not used; adds no value to a package at this time.

Yes, for Debian redistribution I will repackage the source tarball with all files removed which are developed elsewhere and only embedded here as code copies, regardless of whether thay are minified or not.


> I'll try to get this split off into some optional submodule as soon as I can. Thanks for the heads up.

Excellent, but really not crucial for my needs.

Obviously if the code is lagging behind it would be ideal if updated :-)
