### ISSUE TITLE
Compilation error - unhandled assigment to json::tuple property

### ISSUE THREAD

**Issue by SuperRoboWizard** [matrix-construct/construct#97]
During `make install`:
```
libtool: compile:  g++ -std=gnu++17 -DHAVE_CONFIG_H -DIRCD_UNIT -I. -I../include/ircd -I../include -isystem /home/matrix/construct/deps/rocksdb/include -isystem /home/matrix/construct/deps/boost/include -include ircd/ircd.pic.h -DPCH -DNDEBUG -ftls-model=initial-exec -pipe -MT m_room.lo -MD -MP -MF .deps/m_room.Tpo -c m_room.cc  -fPIC -DPIC -o .libs/m_room.o
In file included from json/tuple/tuple.h:164,
                 from json/json.h:39,
                 from ircd.pic.h:47:
json/tuple/set.h: In lambda function:
json/tuple/set.h:168:10: error: call to ‘ircd::json::_assign<ircd::m::invite_3pid, const double&>’ declared with attribute error: Unhandled assignment to json::tuple property
json/tuple/set.h: In lambda function:
json/tuple/set.h:168:10: error: call to ‘ircd::json::_assign<ircd::m::invite_3pid, const long int&>’ declared with attribute error: Unhandled assignment to json::tuple property
make[1]: *** [Makefile:738: m_room.lo] Error 1
```

Debian testing (bullseye), Linux 4.9.0-6-amd64, libc 2.28-10, g++ 8.3.0.
System changed because I moved to a VPS.

**Comment by jevolk** [comment]
Thanks for the report, I've seen this error before a long time ago and thought it was addressed. I'm surprised you're running into it with the environment you indicated because that's pretty close to mine.

If you don't mind, can you include a full build log with configure and make output leading up to the error (e.g. https://ci.appveyor.com/project/jevolk/charybdis-x72h8?fullLog=true)

**Comment by SuperRoboWizard** [comment]
Actually, after deleting the local copy of the repo and re-cloning to get more complete logs, installation went off without a hitch. So I guess this is just an instance of #84.
